[metadata]
name = "Selenized Light Custom"
origin_url = ""

[colors]
background = "#fbf3db"
foreground = "#53676d"
cursor_bg = "#53676d"
cursor_fg = "#d6d0c4"
cursor_border = "#53676d"
selection_bg = "#d5cdb6"
selection_fg = "#333333"
ansi = [
  "#d6d0c4",
  "#d2212d",
  "#489100",
  "#ad8900",
  "#0072d4",
  "#ca4898",
  "#009c8f",
  "#909995",
]
brights = [
  "#909995",
  "#cc1729",
  "#428b00",
  "#a78300",
  "#006dce",
  "#c44392",
  "#00978a",
  "#3a4d53",
]
